# Generated by Django 6.1 on 2026-08-19 21:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight (kg)')),
                ('energy_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='energy (1-5)')),
                ('sleep_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='sleep (1-5)')),
                ('adherence_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='plan adherence (1-5)')),
                ('note', models.TextField(blank=True, verbose_name='how did the week go?')),
                ('trainer_reply', models.TextField(blank=True, verbose_name='coach reply')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='replied at')),
                ('reviewed', models.BooleanField(default=False, verbose_name='reviewed by coach')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'check-in',
                'verbose_name_plural': 'check-ins',
                'ordering': ['-due_date'],
                'unique_together': {('client', 'due_date')},
            },
        ),
        migrations.CreateModel(
            name='CheckInPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checkin_photos/%Y/%m/', verbose_name='photo')),
                ('pose', models.CharField(choices=[('FRONT', 'Front'), ('SIDE', 'Side'), ('BACK', 'Back')], default='FRONT', max_length=10, verbose_name='pose')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='progress.checkin', verbose_name='check-in')),
            ],
            options={
                'verbose_name': 'check-in photo',
                'verbose_name_plural': 'check-in photos',
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('image', models.ImageField(upload_to='progress_photos/%Y/%m/', verbose_name='photo')),
                ('pose', models.CharField(choices=[('FRONT', 'Front'), ('SIDE', 'Side'), ('BACK', 'Back')], default='FRONT', max_length=10, verbose_name='pose')),
                ('consent_public', models.BooleanField(default=False, help_text='Off by default. Only photos you tick here can appear on the public results page. You can withdraw this at any time.', verbose_name='I allow my coach to share this photo publicly')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='consent given at')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'progress photo',
                'verbose_name_plural': 'progress photos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight (kg)')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='waist (cm)')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='chest (cm)')),
                ('arm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='arm (cm)')),
                ('thigh_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='thigh (cm)')),
                ('hip_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='hip (cm)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'body measurement',
                'verbose_name_plural': 'body measurements',
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
