# Generated by Django 6.1 on 2026-08-20 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinphoto',
            name='checkin',
        ),
        migrations.AlterModelOptions(
            name='progressphoto',
            options={'ordering': ['-date', 'pose'], 'verbose_name': 'progress photo', 'verbose_name_plural': 'progress photos'},
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='checkin',
            field=models.ForeignKey(blank=True, help_text='Set when the photo was sent as part of a weekly check-in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='progress.checkin', verbose_name='check-in'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['client', '-date'], name='progress_pr_client__71c6b5_idx'),
        ),
        migrations.DeleteModel(
            name='CheckInPhoto',
        ),
    ]
