# Generated by Django 6.1 on 2026-08-19 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', max_length=5, verbose_name='preferred language'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Egyptian mobile, e.g. 01012345678. Used for WhatsApp.', max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('LOSE_FAT', 'Lose fat'), ('BUILD_MUSCLE', 'Build muscle'), ('RECOMP', 'Body recomposition'), ('STRENGTH', 'Get stronger'), ('GENERAL', 'General fitness')], default='GENERAL', max_length=20, verbose_name='main goal')),
                ('equipment_access', models.CharField(choices=[('FULL_GYM', 'Full gym'), ('HOME_BASIC', 'Home — dumbbells / bands'), ('BODYWEIGHT', 'Bodyweight only')], default='FULL_GYM', max_length=20, verbose_name='equipment access')),
                ('training_days_per_week', models.PositiveSmallIntegerField(default=3, verbose_name='training days available per week')),
                ('injuries', models.TextField(blank=True, verbose_name='injuries or pain')),
                ('allergies', models.TextField(blank=True, verbose_name='food allergies')),
                ('food_dislikes', models.TextField(blank=True, verbose_name='foods you dislike')),
                ('notes', models.TextField(blank=True, verbose_name='anything else')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('client', models.OneToOneField(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='intake', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'intake form',
                'verbose_name_plural': 'intake forms',
            },
        ),
        migrations.CreateModel(
            name='TrainerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_notes', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'trainer note',
                'verbose_name_plural': 'trainer notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
