# Generated by Django 6.1 on 2026-08-19 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('category', models.CharField(choices=[('PROTEIN', 'Protein'), ('CARB', 'Carbohydrate'), ('FAT', 'Fat'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('DAIRY', 'Dairy'), ('COMPOSITE', 'Prepared dish'), ('DRINK', 'Drink'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='category')),
                ('calories_per_100g', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='calories per 100g')),
                ('protein_per_100g', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='protein per 100g')),
                ('carbs_per_100g', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='carbs per 100g')),
                ('fats_per_100g', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='fats per 100g')),
                ('is_egyptian_staple', models.BooleanField(default=False, verbose_name='Egyptian staple')),
            ],
            options={
                'verbose_name': 'food item',
                'verbose_name_plural': 'food items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'supplement',
                'verbose_name_plural': 'supplements',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
        migrations.AlterModelOptions(
            name='nutritionplan',
            options={'verbose_name': 'nutrition plan', 'verbose_name_plural': 'nutrition plans'},
        ),
        migrations.AddField(
            model_name='meal',
            name='alternative_of',
            field=models.ForeignKey(blank=True, help_text='Set this to offer the meal as a swap for another meal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='nutrition.meal', verbose_name='alternative to'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.PositiveIntegerField(help_text='in grams', verbose_name='carbs'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.PositiveIntegerField(help_text='in grams', verbose_name='fats'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionplan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.PositiveIntegerField(help_text='in grams', verbose_name='protein'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='MacroTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calories', models.PositiveIntegerField(verbose_name='target calories')),
                ('target_protein', models.PositiveIntegerField(verbose_name='target protein (g)')),
                ('target_carbs', models.PositiveIntegerField(verbose_name='target carbs (g)')),
                ('target_fats', models.PositiveIntegerField(verbose_name='target fats (g)')),
                ('water_ml', models.PositiveIntegerField(default=2500, verbose_name='daily water (ml)')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macro_target', to='nutrition.nutritionplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'macro target',
                'verbose_name_plural': 'macro targets',
            },
        ),
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.PositiveIntegerField(verbose_name='grams')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_entries', to='nutrition.fooditem', verbose_name='food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='nutrition.meal', verbose_name='meal')),
            ],
            options={
                'verbose_name': 'meal food item',
                'verbose_name_plural': 'meal food items',
            },
        ),
        migrations.CreateModel(
            name='SupplementSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=100, verbose_name='dose')),
                ('timing', models.CharField(choices=[('MORNING', 'Morning'), ('PRE_WORKOUT', 'Pre-workout'), ('POST_WORKOUT', 'Post-workout'), ('WITH_MEAL', 'With a meal'), ('BEFORE_BED', 'Before bed')], default='MORNING', max_length=15, verbose_name='timing')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_schedule', to='nutrition.nutritionplan', verbose_name='plan')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='nutrition.supplement', verbose_name='supplement')),
            ],
            options={
                'verbose_name': 'supplement schedule',
                'verbose_name_plural': 'supplement schedule',
            },
        ),
    ]
