# Generated by Django 6.1 on 2026-08-16 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'شهري (شهر واحد)'), ('QUARTERLY', 'ربع سنوي (3 شهور)'), ('SEMI_ANNUAL', 'نصف سنوي (6 شهور)'), ('ANNUAL', 'سنوي (12 شهر)'), ('CUSTOM', 'مخصص')], default='MONTHLY', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('ACTIVE', 'نشط'), ('EXPIRED', 'منتهي'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
