# Generated by Django 6.1 on 2026-08-19 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='duration in days')),
                ('price_egp', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price (EGP)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'ordering': ['duration_days'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10, verbose_name='status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('INSTAPAY', 'InstaPay'), ('VODAFONE_CASH', 'Vodafone Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CASH', 'Cash in person')], max_length=15, verbose_name='payment method')),
                ('reference_number', models.CharField(blank=True, help_text='The transaction reference shown in your transfer receipt.', max_length=100, verbose_name='reference number')),
                ('amount_egp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='amount paid (EGP)')),
                ('screenshot', models.ImageField(blank=True, upload_to='payment_proofs/%Y/%m/', verbose_name='transfer screenshot')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='status')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='rejection reason')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='subscriptions.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'payment proof',
                'verbose_name_plural': 'payment proofs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
