# Generated by Django 6.1 on 2026-08-19 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('QUADS', 'Quadriceps'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('CALVES', 'Calves'), ('CORE', 'Core'), ('FULL_BODY', 'Full body'), ('CARDIO', 'Cardio')], max_length=12, verbose_name='muscle group')),
                ('equipment', models.CharField(choices=[('BARBELL', 'Barbell'), ('DUMBBELL', 'Dumbbell'), ('MACHINE', 'Machine'), ('CABLE', 'Cable'), ('BODYWEIGHT', 'Bodyweight'), ('KETTLEBELL', 'Kettlebell'), ('BAND', 'Resistance band'), ('OTHER', 'Other')], default='OTHER', max_length=12, verbose_name='equipment')),
                ('video_url', models.URLField(blank=True, verbose_name='demo video')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'catalog exercise',
                'verbose_name_plural': 'exercise library',
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('MAX_WEIGHT', 'Heaviest weight'), ('MAX_REPS', 'Most reps'), ('MAX_VOLUME', 'Best single-set volume'), ('ESTIMATED_1RM', 'Best estimated 1RM')], max_length=15, verbose_name='record type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='value')),
                ('achieved_on', models.DateField(verbose_name='achieved on')),
            ],
            options={
                'verbose_name': 'personal record',
                'verbose_name_plural': 'personal records',
                'ordering': ['-achieved_on'],
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, help_text='Denormalised so history survives the plan being deleted.', max_length=100, verbose_name='exercise name')),
                ('set_number', models.PositiveSmallIntegerField(default=1, verbose_name='set number')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='weight (kg)')),
                ('reps', models.PositiveSmallIntegerField(default=0, verbose_name='reps')),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, help_text='Rate of perceived exertion, 1-10.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE')),
                ('is_warmup', models.BooleanField(default=False, verbose_name='warm-up set')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'set log',
                'verbose_name_plural': 'set logs',
                'ordering': ['set_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('perceived_effort', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='session effort (1-10)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'workout session',
                'verbose_name_plural': 'workout sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order', 'id'], 'verbose_name': 'exercise', 'verbose_name_plural': 'exercises'},
        ),
        migrations.AlterModelOptions(
            name='workoutday',
            options={'ordering': ['order', 'id'], 'verbose_name': 'workout day', 'verbose_name_plural': 'workout days'},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'workout plan', 'verbose_name_plural': 'workout plans'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps_max',
            field=models.PositiveIntegerField(blank=True, help_text='Top of the target rep range. Leave empty for a fixed rep count.', null=True, verbose_name='reps (upper bound)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=90, verbose_name='rest (seconds)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='target weight (kg)'),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Templates have no client and can be cloned onto any client.', verbose_name='is a reusable template'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutday', verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(help_text='Bottom of the target rep range.', verbose_name='reps'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(verbose_name='sets'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='day_name',
            field=models.CharField(max_length=50, verbose_name='day name'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.workoutplan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AddConstraint(
            model_name='workoutplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', True), ('is_template', True)), models.Q(('client__isnull', False), ('is_template', False)), _connector='OR'), name='workoutplan_template_xor_client'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='catalog_exercise',
            field=models.ForeignKey(blank=True, help_text='Link to the library to unlock history, charts and records.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_exercises', to='workouts.exercisecatalog', verbose_name='library exercise'),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='catalog_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='workouts.exercisecatalog', verbose_name='exercise'),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='setlog',
            name='catalog_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_logs', to='workouts.exercisecatalog', verbose_name='library exercise'),
        ),
        migrations.AddField(
            model_name='setlog',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_logs', to='workouts.exercise', verbose_name='plan exercise'),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='set_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='workouts.setlog', verbose_name='set'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workouts.workoutday', verbose_name='day'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workouts.workoutplan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='setlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.workoutsession', verbose_name='session'),
        ),
        migrations.AlterUniqueTogether(
            name='personalrecord',
            unique_together={('client', 'catalog_exercise', 'record_type')},
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['client', '-started_at'], name='workouts_wo_client__0a1bae_idx'),
        ),
        migrations.AddIndex(
            model_name='setlog',
            index=models.Index(fields=['catalog_exercise', '-completed_at'], name='workouts_se_catalog_603e17_idx'),
        ),
    ]
